myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from . import views


urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('about/', views.about, name='about'),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls'))
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='list'),
    path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>', views.post_page, name='page'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateField(auto_now_add=True)
    banner = models.ImageField(default='fallback.jpg', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from . import models


class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug', 'banner']

myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render


def home_page(request):
    # return HttpResponse("Hello! I am homepage.")
    return render(request, 'home.html')


def about(request):
    # return HttpResponse("I am about page")
    return render(request, 'about.html')

posts/views.py
# package imports
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# local imports
from .models import Post
from . import forms


# Create your views here.


def post_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})


def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})


@login_required(login_url='/users/login/')
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form': form})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.


def register_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect('posts:list')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {"form": form})


def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect('posts:new-post')
            else:
                return redirect('posts:list')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def logout_user(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

posts/templates/posts/post_new.html
{% extends "layout.html" %}

{% block title %}Create new post{% endblock title %}

{% block content %}
    <section>
        <h1>Create new post.</h1>

        <form class='form-with-validation' action=" {% url "posts:new-post" %}" method='post' enctype='multipart/form-data'>
            {% csrf_token%}
            {{form}}
            <button class='form-submit'>Add Post</button>
        </form>
    </section>
   
{% endblock content %}

posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
    {{post.title}}
{% endblock title %}

{% block content %}
    <section>
        <h1>{{post.title}}</h1>
        <p>{{post.date}} by {{post.author}}</p>
        <img class='banner' src="{{post.banner.url}}" alt="{{post.title}}">
        <p>{{post.body}}</p>
        
    </section>
{% endblock content %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %} 

{% block title %} Posts {% endblock title %}
  
{% block content %}
    <section>
        <h1>Posts</h1>
        {% for post in posts %}
            <div class="post">
                <h2><a href='{% url 'posts:page' slug=post.slug %}'>{{post.title}}</a></h2>
                <p>{{post.date}} by {{post.author}}</p>
            </div>
        {% endfor %}
    
    </section>

{% endblock content %}
    

templates/about.html
{% extends 'layout.html' %}

{% block title %} About{% endblock title %} 

{% block content %}
<h1>About</h1>
<p>check out my <a href="/">Home</a> page.</p>
{% endblock content %}

templates/home.html
{% extends 'layout.html' %}

{% block title %} Home {% endblock %} 

{% block content %}
<h1>Home</h1>
<p>check out my <a href="/about">About</a> page.</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}" />
    <title>{% block title %} Django App {% endblock %}</title>
  </head>
  <body>
    <nav>
     <div>
        <a href="/" role='img' aria-label='Home' title="Home">🏡</a>
        <a href="/about"  role='img' aria-label='About' title="About">😛</a>
        <a href="{% url  'posts:list' %}"  role='img' aria-label='Posts' title="Posts">📃</a>
     </div>
      <div>
        {% if user.is_authenticated %}
          <a href="{% url  'posts:new-post' %}"  role='img' aria-label='New Post' title="Create">📮</a>

          <form class ='logout' action="{% url  'users:logout' %}" method = 'post'>
            {% csrf_token%} 
            <button class='logout-button' aria-label='User Logout' title="Logout">👋</button>
          </form>
        {% else %}
          <a href="{% url  'users:register' %}"  role='img' aria-label='User Registration' title="Register">🚀</a>
          <a href="{% url  'users:login' %}"  role='img' aria-label='User Login' title="Login">🔏</a>
        {% endif %}
      
      </div>
    </nav>
    <main>{% block content %}{% endblock %}</main>
  </body>
</html>

users/templates/login.html
{% extends "layout.html" %}

{% block title %} Login {% endblock title %}

{% block content %}
    <h1>Log into existing account</h1>
    <form class = "form-with-validation" action='{% url 'users:login'%}' method='post' >
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next }}">
        {% endif %}
        <button class = 'form-submit'>Submit</button>
    </form>
{% endblock content %}

users/templates/register.html
{% extends "layout.html" %}

{% block title %}Register{% endblock title %}

{% block content %}
    <h1>Register a new user</h1>
    <form action="{% url 'users:register'%}" method="post" class = "form-with-validation">
        {% csrf_token %}
        {{form}}
        <button class="form-submit">Submit</button>
    </form>
{% endblock content %}